//Map message bus destination field = field that comes from salesforce
const mapping = {
    mappingName : "Account",
    fields : {
        accountnumber: "AccountNumber",
        name: "Name",
        industrycode: "Industry",
        paymenttermscode: "N/A",
        paymentterms: "mvp_Payment_Terms__c",
        dunsnumber: "mvp_DUNS_Number__c",
        address1_line1: "BillingStreet",
        address1_line2: "BillingStreet",
        address1_line3: "Remove",
        address1_city: "BillingCity",
        address1_stateorprovince: "BillingState",
        address1_postalcode: "BillingPostalCode",
        address1_country: "BillingCountry",
        address1_telephone1: "mvp_Shipping_Phone__c",
        websiteurl: "Website",
        territory: "mvp_Territory__c",
        accountowner: "OwnerId",
        fortune1kflag: "mvp_Fortune_1000_Account__c", //this was documented as a question
        annualrevenue: "mvp_DNB_Revenue_USD__c?",
        noofemployees: "NumberOfEmployees",
        relationshiptype: "mvp_Customer_Type__c",
        headquarters: "mvp_Headquarters__c",
        accountguid: "mvp_Dynamics_Id__c ",
        ryan_focus: "mvp_Focus__c",
        focus: null, //pending
        parentguid: "ParentId -> Parent.mvp_Dynamics_Id__c", //this needs to point to an external object, not sure what to do about this yet (some kind of local lookup?)
        ultimateparentguid: "mvp_Ultimate_Parent_Name__c",
        clientprincipalguid: "mvp_Client_Principal__r.mvp_Dynamics_Id__c",//this needs to point to an external object, not sure what to do about this yet (some kind of local lookup?)
        clientprincipalid: "mvp_Client_Principal__c",
        clientconversiondate: "mvp_Client_Conversion_Date__c",
        ryan_statementcontactid: "mvp_Statement_Contact__c",
        affiliatedrevenue: "mvp_Affiliated_Revenue__c",
        intercompany: "mvp_Intercompany__c",
        ryan_statement: "mvp_Send_Statements__c",
        statecode: "mvp_Status__c",
        originatingleadname: "mvp_Originating_Account_Request__r.Name",//this needs to point to an external object, not sure what to do about this yet (some kind of local lookup?)
        listcategoryname: null, //pending
        salescampaignnew: null, //pending
        industrygroup: "mvp_Industry_Group__c",
        primarynaiccode: "mvp_Primary_NAICS_Code__c",
        primarynaiccodelabel: "mvp_Primary_NAICS_Code_Label__c",
        clientmanagerid: "mvp_Client_Manager__c",
        marketingprofessionalid: "mvp_Primary_Marketing_Professional__c",
        marketingprofessional2id: "mvp_Marketing_Professional_2__c",
        marketingprofessional3id: "mvp_Marketing_Professional_3__c",
        marketingprofessional4id: "mvp_Marketing_Professional_4__c",
        marketingprofessional5id: "mvp_Marketing_Professional_5__c",
        mkpincentive: "mvp_MP_1_Incentive_Split__c",
        mkp2incentive: "mvp_MP_2_Incentive_Split__c",
        mkp3incentive: "mvp_MP_3_Incentive_Split__c",
        mkp4incentive: "mvp_MP_4_Incentive_Split__c",
        mkp5incentive: "mvp_MP_5_Incentive_Split__c",
        accounttier: "mvp_Account_Tier__c",
        ultimateparenttier: "mvp_Ultimate_Parent_Tier__c",
        fp500rank: "Fortune_1000_Rank__c"
    }
}

module.exports = {
    mapping
};

/* Sample Payload From Salesforce as of 2020-04-18
    {
      "attributes": {
        "type": "Account",
        "url": "/services/data/v42.0/sobjects/Account/0014F00000du4LsQAI"
      },
      "Id": "0014F00000du4LsQAI",
      "IsDeleted": false,
      "MasterRecordId": null,
      "Name": "TestConversion",
      "Type": null,
      "RecordTypeId": "0124F000000MJaJQAW",
      "ParentId": "0014F00000b7YcbQAE",
      "BillingStreet": "100 California Street",
      "BillingCity": "San Francisco",
      "BillingState": "CA",
      "BillingPostalCode": "94111",
      "BillingCountry": "United States",
      "BillingLatitude": null,
      "BillingLongitude": null,
      "BillingGeocodeAccuracy": null,
      "BillingAddress": {
        "city": "San Francisco",
        "country": "United States",
        "geocodeAccuracy": null,
        "latitude": null,
        "longitude": null,
        "postalCode": "94111",
        "state": "CA",
        "street": "100 California Street"
      },
      "ShippingStreet": null,
      "ShippingCity": null,
      "ShippingState": null,
      "ShippingPostalCode": null,
      "ShippingCountry": null,
      "ShippingLatitude": null,
      "ShippingLongitude": null,
      "ShippingGeocodeAccuracy": null,
      "ShippingAddress": null,
      "Phone": "1231231234",
      "AccountNumber": null,
      "Website": "testingconversion.com",
      "PhotoUrl": "/services/images/photo/0014F00000du4LsQAI",
      "Industry": null,
      "NumberOfEmployees": 99,
      "Description": null,
      "CurrencyIsoCode": "USD",
      "OwnerId": "0054F000002KM7OQAW",
      "CreatedDate": "2020-04-08T23:03:03.000+0000",
      "CreatedById": "0054F000002KM7OQAW",
      "LastModifiedDate": "2020-04-08T23:03:07.000+0000",
      "LastModifiedById": "0054F000002KM7OQAW",
      "SystemModstamp": "2020-04-08T23:03:07.000+0000",
      "LastActivityDate": null,
      "LastViewedDate": null,
      "LastReferencedDate": null,
      "Jigsaw": null,
      "JigsawCompanyId": null,
      "AccountSource": "Account Creation Request",
      "SicDesc": null,
      "mvp_Fortune_1000_Account__c": "No",
      "mvp_Preferred_Method_of_Contact__c": "Any",
      "mvp_Market_Capitalization__c": null,
      "mvp_Next_Call_Date__c": null,
      "mvp_Software_BD__c": null,
      "mvp_do_not_allow_Bulk_emails__c": true,
      "mvp_Payment_Terms__c": "Net 30",
      "mvp_Primary_Marketing_Professional__c": null,
      "mvp_Marketing_Professional_2__c": null,
      "mvp_Marketing_Professional_3__c": null,
      "mvp_Marketing_Professional_4__c": null,
      "mvp_Marketing_Professional_5__c": null,
      "mvp_Won_Opportunity_Count__c": 0,
      "mvp_Focus__c": null,
      "mvp_Last_Billed__c": null,
      "mvp_Last_Collected__c": null,
      "mvp_Same_as_Main_Address__c": false,
      "mvp_Send_Statements__c": false,
      "mvp_Tax_Direct_Comments__c": null,
      "mvp_MP_1_Incentive_Split__c": null,
      "mvp_MP_2_Incentive_Split__c": null,
      "mvp_MP_3_Incentive_Split__c": null,
      "mvp_MP_4_Incentive_Split__c": null,
      "mvp_MP_5_Incentive_Split__c": null,
      "mvp_Incentive_Split_Total__c": 0,
      "mvp_Territory__c": null,
      "qualtrics__NPS_Date__c": null,
      "mvp_Ultimate_Parent_Name__c": "<a href="/0014F00000bebP2" target="_blank">General Electric Company</a>",
      "mvp_do_not_email__c": true,
      "mvp_do_not_allow_faxes__c": false,
      "mvp_do_not_phone__c": true,
      "mvp_do_not_postal_mails__c": true,
      "mvp_Send_Marketing_Materials__c": true,
      "mvp_SharePoint_URL__c": null,
      "mvp_DUNS_Number__c": null,
      "mvp_Avention_Key__c": null,
      "mvp_2010_Industry_Name__c": null,
      "mvp_Industry_Group__c": null,
      "mvp_Industry_Sector__c": null,
      "mvp_Primary_NAICS_Code__c": null,
      "mvp_Primary_NAICS_Code_Label__c": null,
      "mvp_Legacy_SharePoint_URL__c": null,
      "mvp_Reported_Currency__c": null,
      "mvp_RGS_Account__c": null,
      "mvp_Anti_Fraud_Corruption_Check__c": false,
      "mvp_Annual_Assets_USD_MM__c": null,
      "mvp_Account_Tier__c": null,
      "MVP_Assist_1__c": null,
      "MVP_Assist_2__c": null,
      "MVP_Advocacy_1__c": null,
      "MVP_Advocacy_2__c": null,
      "MVP_Executive_Assistant_1__c": null,
      "MVP_Executive_Assistant_2__c": null,
      "mvp_Originating_Account_Request__c": "00Q4F000005ydRDUAY",
      "mvp_Originating_Lead_Creator__c": "0054F000002KM7OQAW",
      "mvp_Number_of_Associated_Tax_Direct__c": 0,
      "qualtrics__Net_Promoter_Score__c": null,
      "mvp_Tax_Direct_Expiration__c": null,
      "mvp_Dynamics_Id__c": null,
      "mvp_Intercompany__c": null,
      "mvp_Account_Priority__c": null,
      "mvp_APD_Account_History__c": null,
      "mvp_APD_Not_Tried__c": null,
      "mvp_APD_Not_working_well__c": null,
      "mvp_APD_Biggest_Obstacle__c": null,
      "mvp_APD_Working_well__c": null,
      "mvp_APD_Help_Acknowledged__c": null,
      "mvp_APD_Why_Unproductive__c": null,
      "mvp_APD_Account_Summary__c": null,
      "mvp_APD_Biggest_Competitor_Blocker__c": null,
      "mvp_APD_Other_Providers__c": null,
      "mvp_APD_Do_Themselves__c": null,
      "mvp_Legacy_Client_Number__c": null,
      "mvp_Audit_Firm__c": null,
      "mvp_Fiscal_Year_Ends__c": null,
      "mvp_Status__c": "Active",
      "mvp_Status_Reason__c": null,
      "mvp_APD_Relationship_Summary__c": null,
      "mvp_Region_Canada__c": null,
      "mvp_Strength_of_Relationship__c": null,
      "LID__LinkedIn_Company_Id__c": null,
      "mvp_Ryan_Industry__c": null,
      "mvp_Statement_Contact__c": null,
      "mvp_DNB_Revenue_EUR__c": null,
      "mvp_Client_Principal__c": null,
      "mvp_Last_Tax_Review_Date__c": null,
      "mvp_Net_New__c": false,
      "mvp_Last_Completed_Engagement_Date__c": null,
      "mvp_Open_Revenue__c": 0,
      "mvp_Open_Deals__c": 0,
      "mvp_Ultimate_Parent_Tier__c": "Platinum",
      "mvp_Total_Open_Deals__c": 0,
      "mvp_Total_Open_Revenue__c": 0,
      "mvp_Account_Auto_Number_Placeholder__c": "00047",
      "mvp_Annual_Revenue_CA__c": null,
      "mvp_Hierarchal_Level__c": null,
      "mvp_Ownership_Code__c": null,
      "Ultimate_Parent_ID__c": "0014F00000bebP2",
      "mvp_Lifetime_Tax_Savings__c": 0,
      "mvp_Lifetime_Revenue_Generated__c": 0,
      "DXP_Hierarchy_Classification__c": "Child",
      "mvp_User_is_CP__c": false,
      "mvp_User_is_Owner__c": false,
      "mvp_Merged__c": false,
      "mvp_New_Client_Date__c": null,
      "mvp_Previous_Primary_Marketing_Pro__c": null,
      "mvp_Previous_Marketing_Professional_2__c": null,
      "mvp_Previous_Marketing_Professional_3__c": null,
      "mvp_Previous_Marketing_Professional_4__c": null,
      "mvp_Previous_Marketing_Professional_5__c": null,
      "mvp_Previous_MP_1_Incentive_Split__c": null,
      "mvp_Previous_MP_2_Incentive_Split__c": null,
      "mvp_Previous_MP_3_Incentive_Split__c": null,
      "mvp_Previous_MP_4_Incentive_Split__c": null,
      "mvp_Previous_MP_5_Incentive_Split__c": null,
      "mvp_Previous_Client_Principal__c": null,
      "mvp_Primary_Contact__c": null,
      "mvp_DNB_Revenue_GBP__c": null,
      "mvp_MP_Changed__c": false,
      "mvp_Previous_Name__c": null,
      "mvp_Inactive_Client_Date__c": null,
      "mvp_Credit_On_Hold__c": false,
      "mvp_Customer_Type__c": null,
      "Fortune_1000_Rank__c": null,
      "Is_Headquarters__c": false,
      "mvp_do_not_allow_Bulk_Postal_Mail__c": false,
      "mvp_Client_Conversion_Date__c": null,
      "mvp_List_Category__c": null,
      "mvp_Open_Deals_Date__c": null,
      "mvp_Client_Manager__c": null,
      "mvp_Affiliated_Revenue__c": false,
      "mvp_CFT_Account__c": false,
      "mvp_Convert_to_Client__c": false,
      "mvp_DNB_Assets__c": null,
      "mvp_dnb_primarynaics2012__c": null,
      "mvp_dnb_primaryuk2007sic__c": null,
      "mvp_dnb_primaryus87sic__c": null,
      "mvp_DNB_Revenue__c": null,
      "mvp_Headquarters__c": false,
      "mvp_avgsurveyscore_Date__c": null,
      "mvp_DNB_Assets_EUR__c": null,
      "mvp_DNB_Assets_GBP__c": null,
      "mvp_DNB_Primary_NAICS_2012_Label__c": null,
      "mvp_DNB_Primary_UK_2007_SIC_Label__c": null,
      "mvp_DNB_Primary_US_87_SIC_Label__c": null,
      "mvp_DNB_Report_ISO_3_Currency_Code__c": null,
      "mvp_DNB_Revenue_USD__c": null,
      "mvp_Shipping_Phone__c": null,
      "Tax_Direct_Expiration_Date__c": null
    }
*/
