//Map message bus destination field = field that comes from salesforce
const mapping = {
    mappingName : "Contact",
    fields : {
        fullname : "Name",
        firstName : "FirstName",
        lastName : "LastName",
        nickName : null,
        jobTitle : "Title",
        address1Line1 : "MailingStreet",
        address1Line2 : null,
        address1City : "MailingCity",
        address1Country : "MailingCountry",
        address1StatePicker : "",
        address1PostalCode : "MailingPostalCode",
        address1StateCode : "MailingState",
        address2Line1 : "",
        address2Line2 : "",
        address2City : "",
        address2Country : "",
        address2StatePicker : "",
        address2PostalCode : "",
        address2StateCode : "",
        telephone1 : "",
        telephone2 : "",
        telephone3 : "",
        mobilePhone : "MobilePhone",
        emailAddress : "Email",
        salutation : "Salutation",
        contactTypeId : "",
        accountGuid : null
    }
}

module.exports = {
    mapping
};

/* Sample Payload From Salesforce as of 2020-04-18
    {
      "attributes": {
        "type": "Contact",
        "url": "/services/data/v42.0/sobjects/Contact/0034F00000TLSwKQAX"
      },
      "Id": "0034F00000TLSwKQAX",
      "IsDeleted": false,
      "MasterRecordId": null,
      "AccountId": "0014F00000W6tLLQAZ",
      "LastName": "Doe",
      "FirstName": "John",
      "Salutation": null,
      "MiddleName": null,
      "Suffix": null,
      "Name": "John Doe",
      "RecordTypeId": null,
      "MailingStreet": null,
      "MailingCity": null,
      "MailingState": null,
      "MailingPostalCode": null,
      "MailingCountry": null,
      "MailingLatitude": null,
      "MailingLongitude": null,
      "MailingGeocodeAccuracy": null,
      "MailingAddress": null,
      "Phone": "555-555-5555",
      "Fax": null,
      "MobilePhone": "777-777-7777",
      "ReportsToId": null,
      "Email": "jdoe@fakeemail.com",
      "Title": null,
      "Department": null,
      "CurrencyIsoCode": "USD",
      "OwnerId": "0056g000000NJMCAA4",
      "CreatedDate": "2019-11-07T00:14:47.000+0000",
      "CreatedById": "0056g000000NJMCAA4",
      "LastModifiedDate": "2019-11-07T00:14:47.000+0000",
      "LastModifiedById": "0056g000000NJMCAA4",
      "SystemModstamp": "2019-11-07T00:14:47.000+0000",
      "LastActivityDate": null,
      "LastCURequestDate": null,
      "LastCUUpdateDate": null,
      "LastViewedDate": null,
      "LastReferencedDate": null,
      "EmailBouncedReason": null,
      "EmailBouncedDate": null,
      "IsEmailBounced": false,
      "PhotoUrl": "/services/images/photo/0034F00000TLSwKQAX",
      "Jigsaw": null,
      "JigsawContactId": null,
      "IndividualId": null,
      "qualtrics__Informed_Consent_Date__c": null,
      "qualtrics__Informed_Consent__c": false,
      "qualtrics__Last_Survey_Invitation__c": null,
      "qualtrics__Last_Survey_Response__c": null,
      "qualtrics__Net_Promoter_Score__c": null,
      "mvp_Last_Contacted_Date__c": null,
      "mvp_Gender__c": null,
      "mvp_Marital_Status__c": null,
      "mvp_Children_s_Names__c": null,
      "mvp_Education__c": null,
      "mvp_Employee_ID__c": null,
      "mvp_Manager_Name__c": null,
      "mvp_Pager__c": null,
      "mvp_Newsletter__c": null,
      "mvp_Spouses_Name__c": null,
      "Tax_Developments__c": null,
      "mvp_Training_Opportunities__c": null,
      "mvp_Relationship_Type__c": null,
      "mvp_Manager_Phone__c": null,
      "mvp_Use_as_Billing_Contact__c": false,
      "mvp_Anniversary__c": null,
      "mvp_Home_Phone_2__c": null,
      "LID__Languages__c": null,
      "LID__Level__c": null,
      "LID__LinkedIn_Company_Id__c": null,
      "LID__LinkedIn_Member_Token__c": null,
      "LID__No_longer_at_Company__c": null,
      "LID__Session_Id__c": "00D4F0000001591!ARcAQHxW_g4Zr3EXS855TajTWkoTg3WJ.fVIrLYDLWp9_fwCbpGBcfPXxDBaEDq_VBXao2S3QEf8Rr.WoI3dxm4nv8ZAm_d.",
      "mvp_Company_Phone__c": null,
      "mvp_Dynamics_Id__c": null,
      "mvp_Annual_Income__c": null,
      "mvp_Sync_Address_with_Account__c": null,
      "mvp_Credit_On_Hold__c": false,
      "mvp_Yomi_Full_Name__c": null,
      "mvp_Business_Phone__c": null,
      "mvp_Send_Annual_CSE__c": false,
      "mvp_Ryan_Alumni__c": false,
      "mvp_PTS_SFDC_Record__c": false,
      "mvp_PTS_Record__c": false,
      "mvp_Contact_Type__c": null,
      "mvp_Client_Support_Information__c": false,
      "mvp_Add_to_Marketing_List__c": false,
      "mvp_Preferred_Method_of_Contact__c": null,
      "mvp_Do_not_allow_Bulk_Mails__c": false,
      "mvp_Do_not_allow_Phone_Calls__c": false,
      "mvp_Do_not_allow_Mails__c": false,
      "mvp_Send_Marketing_Materials__c": false,
      "mvp_Exchange_Rate__c": null,
      "mvp_Owning_User__c": null,
      "mvp_Client_Support_Information_Name__c": null,
      "mvp_Alumni_Name__c": null,
      "mvp_Salutation_Name__c": null,
      "mvp_Status__c": null,
      "mvp_Status_Reason__c": null,
      "mvp_Parent_Account__c": null,
      "mvp_Tax_Direct_Expiration_Date__c": null
    },
*/