//Map message bus destination field = field that comes from salesforce
const mapping = {
    mappingName : "Engagement",
    fields : {
        engagementguid: "mvp_Dynamics_Id__c",
        salesforceid: "Id",
        engagementid: "NeedFieldCreated",
        engagementdesc: "mvp_Description__c",
        billingcontactid: "ClientBillingContact",
        periodbegin: "Needfieldcreated",
        periodend: "CompletedDate",
        agreementdate: "PendingToSeeIfNeeded",
        legalentity: "RyanLegalEntity",
        practicearea: "PracticeArea",
        parentpracticearea: "ParentPracticeArea",
        servicetype: "ServiceType",
        jurisdiction: "Jurisdiction",
        isocurrencycode: "CurrencyCode",
        ryancompany: "RyanLegalEntity",
        parentaccountname: "Remove",
        feetype: "Needfieldcreated",
        state: "Remove",
        region: "Needfieldcreated",
        statuscode: "Status",
        active: "RemoveRYANtoapplylogic",
        ultimate_parent: "RemoveRYANtoapplylogic",
        ultimateparentaccountguid: "RemoveRYANtoapplylogic",
        rank: "RemoveRYANtoapplylogic",
        createdon: "createdDate",
        datefulfilled: "Needfieldcreated",
        modifiedon: "LastModifiedDate",
        ratetableid: "RateTableID",
        agreementtype: "OnContract", 
        executeddate: "OnContract", 
        ryancompanycode: "RemoveRYANtoapplylogicfromLegalEntity",
        thirdpartymarketerincentive: "Needfieldcreated",
        externallawfirm: "Needfieldcreated",
        ryanadvocacy: "Needfieldcreated",
        ryan_acquisitionincentivesnew: "Needfieldcreated",
        ryanattorney: "Needfieldcreated",
        referencenumber: "RemoveRyantoapplylogicfromcontract",
        statusupdatemeetinglast: "RemoveRyantofollowup",
        statusupdatemeetingnext: "RemoveRyantofollowup",
        accountguid: "AccountGUID",
        accountid: "ACCOUNTID",
        engagementletterexecutiondate: "RemoveRyantoapplylogicfromcontract",
        ryan_affiliatedaccountid: "Needfieldcreated",
        affiliatedengagementid: "Needfieldcreated",
        ponumber: "Needfieldcreated",
        ryan_acquisitionsourcename: "Needfieldcreated",
        intercompanyaccountnumber: "Needfieldcreated",
        intercompanyengagementid: "Needfieldcreated",
        ryan_taxdirectsupport: "mvp_Tax_Direct_Support__c",
        contractguid: "ContractGUID",
        contractid: "ContractId",
        ryan_terms: "PaymentTerms",
        ryan_additionalidentifier: "Needfieldcreated",
        ryan_primaryengagementcode2: "Needfieldcreated",
        acquisitionincentive: "AcquisitionIncentivesNew",
        acquisitionsource: "sameasrow55",
        opportunityorigin: "origin",
        opportunityoriginsource: "origin",
        opportunitytype: "OpportunityType",
        potentialfees: "Needfieldcreated",
        salescampaigngroupname: "Needfieldcreated",
        sourcecampaign: null,
        dailyfinancecharge: "Needfieldcreated",
        iskovelagreement: "Needfieldcreated",
        marketingprofessionalguid: "PrimaryMarketingProfessional",
        marketingprofessional2guid: "MarketingProfessional2",
        marketingprofessional3guid: "MarketingProfessional3",
        marketingprofessional4guid: "MarketingProfessional4",
        marketingprofessional5guid: "MarketingProfessional5",
        mkpincentive: "MP1IncentiveSplit",
        mkp2incentive: "PreviousIncentiveSplit2",
        mkp3incentive: "PreviousIncentiveSplit3",
        mkp4incentive: "PreviousIncentiveSplit4",
        mkp5incentive: "PreviousIncentiveSplit5",
        engagementmanagerguid: "EngagementManager",
        engagementprincipalguid: "EngagementPrincipal",
        clientprincipalguid: "mvp_Client_Principal__c",
        assist1guid: "Needfieldcreated",
        assist2guid: "Needfieldcreated",
        billingcoordinatorguid: "BillingCoordinator",
        clientportallongname: "Needfieldapiname",
        clientportalshortname: "Needfieldapiname",
        auditstartisopen: "Needfieldapiname",
        auditendisopen: "Needfieldapiname",
        primaryengagement: "PrimaryEngagement",
        acquisitionincentivesnew: "AcquisitionIncentivesNew"
    }
}

module.exports = {
    mapping
};

/* Sample Payload From Salesforce as of 2020-04-18
*/